rcacho/static-web-app

.eslintrc.json
.prettierrc
package.json
src/components/Calendar.tsx
src/components/Legend.tsx
src/components/RightBar.tsx
src/components/Theme.tsx
src/components/TopBar.tsx
src/components/calendarComponents/DayMonthView.tsx
src/components/calendarComponents/DayYearView.tsx
src/components/menu/MainMenuAdmin.tsx
src/pages/_app.tsx
src/pages/about.tsx
src/pages/api/auth/[...nextauth].ts
src/pages/api/time.ts
src/pages/index.tsx

- random change
- no tests
- non-UI change

random change

---

.idea/inspectionProfiles/Project_Default.xml
src/components/Calendar.tsx
src/components/TopBar.tsx
src/components/calendarComponents/DayMonthView.tsx
src/components/calendarComponents/DayYearView.tsx
src/components/menu/RightMenu.tsx
src/components/menu/RightMenuButton.tsx
src/components/menu/menuButtons/addEvent/AddEventRender.tsx
src/components/menu/menuButtons/changeCategories/AddNewCategory.tsx
src/components/menu/menuButtons/changeCategories/ChangeCategories.tsx
src/components/menu/menuButtons/changeCategories/EditCategory.tsx
src/components/menu/menuButtons/changeEvents/AddEventRender.tsx
src/components/menu/menuButtons/changeEvents/ChangeDeleteEvent.tsx
src/components/menu/menuButtons/changeEvents/EditEvent.tsx
src/pages/index.tsx

Menu bar j

---

src/components/TopBar.tsx
src/components/calendar/Calendar.tsx
src/components/calendar/CalendarNavigator.tsx
src/components/calendar/Day.tsx
src/components/calendar/Month.tsx
src/components/calendar/Year.tsx
src/components/menu/RightMenu.tsx
src/components/menu/RightMenuButton.tsx
src/components/menu/menuButtons/changeEvents/ChangeDeleteEvent.tsx
src/pages/index.tsx
src/store/CalendarContext.tsx

Created a global calendar store to minimise prop drilling + refactored code from TopBar.
Minor bug fixes and some minor UI improvements here and there too.

Refactoring Part 2

---

src/components/calendar/CalendarNavigator.tsx
src/components/menu/Buttons.tsx
src/components/menu/MainMenuItems.tsx
src/components/menu/RightMenu.tsx
src/components/menu/menuButtons/changeCategories/AddNewCategory.tsx
src/components/menu/menuButtons/changeCategories/ChangeCategories.tsx
src/components/menu/menuButtons/changeCategories/ColourPicker.tsx
src/components/menu/menuButtons/changeCategories/EditCategory.tsx
src/components/menu/menuButtons/changeCategories/SymbolPicker.tsx
src/components/menu/menuButtons/changeEvents/AddEventRender.tsx
src/components/menu/menuButtons/changeEvents/EditEvent.tsx
src/components/menu/menuButtons/editAdmins/AddAdmin.tsx
src/components/menu/menuButtons/editAdmins/AddRemoveMain.tsx
src/components/menu/menuButtons/editAdmins/RemoveAdmin.tsx
src/styles/globals.css
yarn.lock

Added admin and category menus; some changes to top bar look

Main menu admin

---

src/components/calendar/Month.tsx

some small tweaks i have to do:
- if the first working day is not monday: working hours becomes
160 + (8 * working days in first week of first month)
- if the last working day is not fri/sat/sun: working hours becomes 
160 + (8 * (5 - working days in first week of first month))  [i.e the remaining week of december]
no need to add 8 in february for leap year cuz it will be moved into december so to say
need additional check for february (will always have 160 working hours i think, gotta double check)

Working hours

---

src/components/calendar/Day.tsx

fix spacing for working hours

---

src/components/calendar/Day.tsx

icons doneeeeee !!!!! yaaayyyaayay

updated icon order

---

src/components/calendar/Calendar.tsx
src/components/calendar/Day.tsx
src/components/calendar/Month.tsx
src/components/calendar/Year.tsx
src/store/CalendarContext.tsx

the spacing for the month view exists but I cannot figure out how to make it better.  also the color is still light blue i am not sure what to make of the color

Grid weeks

---

src/components/calendar/Month.tsx
src/components/calendar/Year.tsx

adjusted month title and working hours in month view

adjusting month to side and working hours

---

next.config.js

change the config file

---

src/store/CalendarContext.tsx

minor fixes

---

src/interfaces/User.ts
src/pages/api/category.ts
src/pages/api/category/[id].ts
src/pages/api/user.ts
src/pages/api/user/[id].ts
src/pages/api/user/check_notifications/[id].ts
src/utils/DatabaseConnector.ts
src/utils/dao/CategoryDAO.ts
src/utils/dao/NotificationDAO.ts
src/utils/dao/UserDAO.ts
yarn.lock

Add some error handling to user and category API, update notification API to use notification_check instead of last_login

Minor error handling, notification table column change

---

.gitignore
src/components/Legend.tsx
src/components/TopBar.tsx
src/components/calendar/Calendar.tsx
src/components/calendar/CalendarNavigator.tsx
src/components/calendar/Day.tsx
src/components/calendar/Month.tsx
src/components/calendar/Year.tsx
src/components/legendComponents/CategoryList.tsx
src/components/menu/RightMenu.tsx
src/components/menu/RightMenuButton.tsx
src/components/menu/menuButtons/changeCategories/AddNewCategory.tsx
src/components/menu/menuButtons/changeCategories/ChangeCategories.tsx
src/components/menu/menuButtons/changeCategories/EditCategory.tsx
src/components/menu/menuButtons/changeCategories/SymbolPicker.tsx
src/components/menu/menuButtons/changeEvents/AddEventRender.tsx
src/components/menu/menuButtons/changeEvents/ChangeDeleteEvent.tsx
src/components/menu/menuButtons/changeEvents/EditEvent.tsx
src/components/menu/menuButtons/editAdmins/AddAdmin.tsx
src/components/menu/menuButtons/editAdmins/RemoveAdmin.tsx
src/pages/index.tsx
src/store/Icons.ts
src/styles/globals.css
yarn.lock

- not perfect: it doesn't render unless you click in a month and back out hmm

preliminary rendering for days

---

src/pages/api/admin-membership.ts
src/utils/APIManager.ts

make dumber

---

src/pages/api/admin-membership.ts

try other claim

---

src/pages/api/admin-membership.ts

fix field names

---

package.json
src/pages/api/category.ts
src/pages/api/category/[id].ts
src/pages/api/event.ts
src/pages/api/event/[id].ts
src/pages/api/filter.ts
src/pages/api/notification/[id].ts
src/pages/api/time.ts
src/pages/api/user.ts
src/pages/api/user/[id].ts
src/pages/api/user/check_notifications/[id].ts
src/utils/APIManager.ts
src/utils/middleware/Auth.ts
src/utils/middleware/Cors.ts
yarn.lock

Add claims from external source

---

src/store/APIContext.tsx

Fix typo in Admin claim

---

src/components/menu/menuButtons/changeEvents/AddEventRender.tsx
src/components/menu/menuButtons/changeEvents/DeleteEventPopUp.tsx
src/store/APIContext.tsx

adding an event results in a popup showing that it has been added
refer to test plan
i forgot
it popups up twice, but I don't know why.

added popup for adding event

---

src/components/calendar/Day.tsx
src/components/menu/MainMenuItems.tsx
src/components/menu/menuButtons/changeCategories/AddNewCategory.tsx
src/components/menu/menuButtons/changeCategories/ChangeCategories.tsx
src/components/menu/menuButtons/changeCategories/SymbolPicker.tsx
src/components/menu/menuButtons/changeCategories/popups/AddCatPopUp.tsx

Styling etc

---

src/components/menu/menuButtons/changeEvents/DeleteEventPopUp.tsx

added popup
test plan
i keep forgetting

add delete event popup confirmation

---

src/components/menu/MainMenuItems.tsx
src/components/menu/RightMenu.tsx
src/components/menu/menuButtons/changeEvents/AddEventRender.tsx
src/components/menu/menuButtons/changeEvents/EditEvent.tsx

add edit event success popup

---

src/components/Legend.tsx
src/components/menu/RightMenuButton.tsx
src/components/menu/menuButtons/changeCategories/popups/AddCatPopUp.tsx
src/components/menu/menuButtons/changeCategories/popups/DeleteCategoryPopUp.tsx
src/components/menu/menuButtons/changeCategories/popups/EditCatPopUp.tsx
src/components/menu/menuButtons/changeEvents/ChangeDeleteEvent.tsx
src/components/menu/menuButtons/changeEvents/DeleteEventPopUp.tsx
src/components/menu/menuButtons/changeEvents/EditEvent.tsx
src/store/APIContext.tsx

rendered events should update when changes are made

made events render on update

---

src/components/alert/AlertButton.tsx
src/interfaces/Alert.ts
src/store/APIContext.tsx
src/utils/APIManager.ts

- When an event is added / updated, a notification appears
- Notifications are updated when the page is refreshed
- Notifications are marked as read when the notification bar is opened

Notifications

---

src/pages/api/category.ts
src/pages/api/category/[id].ts
src/pages/api/event.ts
src/pages/api/event/[id].ts
src/pages/api/filter.ts
src/utils/InternalErrorHandler.ts
src/utils/middleware/Auth.ts

Improve Error Handling

---

src/utils/middleware/Auth.ts

- fixed `API resolved without sending a response for <endpoint>, this may result in stalled requests.`
- improved speed by moving client for jwt parsing out of function (the first request is still slow but faster after)

Fix resolved without sending

---

src/pages/api/notification-check.ts
src/utils/dao/NotificationCheckDAO.ts
src/utils/dao/NotificationDAO.ts

- fix notification query use of notification checks
- fix const names (was still user)
- fix insert of notiication check

fix notication checking

---

src/components/alert/AlertButton.tsx

- fixed date on notifications which were off by a month
- changed the string in notifications to make sense for all actions

Fix Notification Dates

---

src/components/menu/menuButtons/printCalendar/PrintCalPopUp.tsx

format change to account for style updates

fix print fit

---

src/components/calendar/Day.tsx
src/components/menu/menuButtons/changeCategories/popups/AddCatPopUp.tsx
src/components/menu/menuButtons/changeCategories/popups/EditCatPopUp.tsx

Final commit ??? making categories rerender on day
